### ISSUE TITLE
lint-everything: Error: No files matching '../quake' were found.

### ISSUE THREAD

**Issue by samreid** [phetsims/quake#3]
CT reported:

```
~/apache-document-root/main/perennial$ grunt lint-everything
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: No files matching '../quake' were found.
  at FileEnumerator.iterateFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/cli-engine/file-enumerator.js:317:27)
  at iterateFiles.next (<anonymous>:null:null)
  at CLIEngine.executeOnFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:771:48)
  at ESLint.lintFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/eslint/eslint.js:563:23)
  at lint (/Users/samreid/apache-document-root/main/chipper/js/grunt/lint.js:93:32)
  at /Users/samreid/apache-document-root/main/perennial/js/grunt/Gruntfile.js:515:13
  at Object.<anonymous> (/Users/samreid/apache-document-root/main/perennial/js/grunt/Gruntfile.js:70:13)
  at Object.thisTask.fn (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/util/task.js:293:12)
  at Task.start (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/util/task.js:302:5)
  at Object.grunt.tasks (/Users/samreid/apache-document-root/main/perennial/node_modules/grunt/lib/grunt.js:173:8)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:67:15)
  at Liftoff.execute (/usr/local/lib/node_modules/grunt-cli/node_modules/liftup/index.js:202:12)
  at module.exports (/usr/local/lib/node_modules/grunt-cli/node_modules/flagged-respawn/index.js:51:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/liftup/index.js:192:5)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/liftup/index.js:155:7)
  at processTicksAndRejections (internal/process/task_queues.js:77:11)

Full Error details:
Error: No files matching '../quake' were found.
```

Lint requires to find files, so we must either add at least one *.js file in quake, or remove it from the list of repos to lint.  If we add it to the list of repos not to lint, we may forget to remove it when we add a *.js file, so I'll just create a short *.js file for now.  It can be deleted when there are other *.js files.

**Comment by samreid** [comment]
Proposed temporary fix in the commit.  @jbphet can you please review?

**Comment by jbphet** [comment]
Thanks @samreid.  I changed the file name and added an explanation in the file.

I also added a TODO in the file and referenced this issue.  I'm going to remove the "ready-for-review" label and defer this issue for now, but I'll keep it around as a reminder to remove the file at some point.  Once the file is removed, this issue can be closed.

**Comment by jbphet** [comment]
There is a grunt file in the `js` directory now, as well as `js` files in other places.  Lint and lint-everything are both passing.  I think it's safe to remove the stub.js file.  I'll try it, and keep an eye on CT.

**Comment by jbphet** [comment]
CT looks good, closing.
